<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UH5N0DV" failures="1" tests="9" name="TestNG" time="0.05" errors="0" timestamp="2022-07-04T09:53:51 IST">
  <testcase classname="Demo_Package.TestNG_DemoClass" name="MobilePersonalLoan" time="0.006"/>
  <testcase classname="Demo_Package.TestNG_DemoClass" name="APIPersonalLoan" time="0.001"/>
  <testcase classname="Demo_Package.TestNG_DemoClass" name="WebPersonalLoan" time="0.001"/>
  <testcase classname="Demo_Package.TestNG_DemoClass2" name="WebCarLoan" time="0.001"/>
  <testcase classname="Demo_Package.TestNG_DemoClass2" name="MobileCarLoan" time="0.001"/>
  <testcase classname="Demo_Package.TestNG_DemoClass2" name="APICarLoan" time="0.0"/>
  <testcase classname="Demo_Package.TestNG_DemoClass3" name="APIHomeLoan" time="0.0"/>
  <testcase classname="Demo_Package.TestNG_DemoClass3" name="MobileHomeLoan" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Demo_Package.TestNG_DemoClass3.MobileHomeLoan(TestNG_DemoClass3.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- MobileHomeLoan -->
  <testcase classname="Demo_Package.TestNG_DemoClass3" name="WebHomeLoan" time="0.0"/>
</testsuite> <!-- TestNG -->
